# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-qt5 mingw-w64-x86_64-qtwebkit
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          mkdir build
          cd build
          cmake ..
          ninja
      - name: Building the installer
        run: |
          cd build
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "script.iss"
        shell: cmd
      - name: Upload the installer as an artifact
        uses: actions/upload-artifact@v2
        #if: ${{ github.event_name != 'pull_request' }}
        with:
          path: "build/*Setup.exe"
          name: wininstaller-innosetup
